### ISSUE TITLE
Tiny issues

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#177]
(On going)
![image](https://user-images.githubusercontent.com/1689815/53408387-9a7d8e80-39be-11e9-8bc2-50fc987eabd0.png)
> replace with small camera+ icon ?

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/53408587-242d5c00-39bf-11e9-9b3d-0dab59efbbfd.png)
Make nutrition table horizontally scrollable, so that we can have all the width we need for all the possible columns
(Per 100G, Per Portion, Per 100G prepared, Per Portion prepared)

**Comment by teolemon** [comment]
- Remove the scan icon on the product page from search
- Replace it by a pencil icon linking to the webview edit for now
- Remove the edit link
- If the user is not logged in when clicking on the pencil icon, propose to login/signup
- make the add new image take the max horizontal layout with a layout like this
![image](https://user-images.githubusercontent.com/1689815/53408799-bd5c7280-39bf-11e9-9fab-72705d5f84fd.png)

**Comment by teolemon** [comment]
- Text for allergen alert is showing even if you haven't defined any allergen
 - You can't access the allergen screen
@philippeauriach

**Comment by teolemon** [comment]
- Crash on login attempt

**Comment by philippeauriach** [comment]
**TODO list**
- [x] replace with small camera+ icon ?
- [ ] Make nutrition table horizontally scrollable, so that we can have all the width we need for all the possible columns
- [ ] (Per 100G, Per Portion, Per 100G prepared, Per Portion prepared)
- [ ] Remove the scan icon on the product page from search
- [ ] Replace it by a pencil icon linking to the webview edit for now
- [ ] Remove the edit link
- [ ] If the user is not logged in when clicking on the pencil icon, propose to login/signup
- [ ] make the add new image take the max horizontal layout with a layout like this
- [x] Crash on login attempt
- [ ] Text for allergen alert is showing even if you haven't defined any allergen
- [x] You can't access the allergen screen

**Comment by aleene** [comment]
Is prepared already accessible via the api?

**Comment by aleene** [comment]
![screen shot 2019-02-27 at 16 10 38](https://user-images.githubusercontent.com/1329905/53500290-5798e500-3aaa-11e9-934a-4326b524f001.png)

**Comment by teolemon** [comment]
@aleene append _prepared to fields
@aleene was fixed by @philippeauriach in an upcoming PR

**Comment by teolemon** [comment]
I'm closing this bug since the matching PR has been fixed. I'm now opening individual bugs as we get closer to release.
