### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#189]
- [ ] Screenshots
- [ ] Changelogs
- [ ] Bugs
- [ ] Check it works in all languages on display (check with pt_BR)
- [ ] Check it works in all languages on product addition (check with pt_BR) (notloggedin)
- [ ] Check it works in all languages on product addition (check with pt_BR) (loggedin)
- [ ] Check allergen alert works well
- [ ] Check history deletion works well
- [ ] Check what happens if the server crashes
