### ISSUE TITLE
Add support for displaying the Eco-Score.

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#744]
Add support for displaying the Eco-Score

### Preview

![image](https://user-images.githubusercontent.com/1689815/97958008-a6813c80-1dac-11eb-8bca-4d336c10e85e.png)
Here's what it would look like with a placeholder. We would loose the product image for better legibility. cc @stephanegigandet @openfoodfacts/openfoodfacts-ios 

### Task overview

- [ ] Clone the system that displays Nutri-Score on the scan card
- [ ] Change the server request url to ecoscore (server-side issue: https://github.com/openfoodfacts/openfoodfacts-server/issues/4262)
- [ ] If (and only if) the server sends back a proper value (a, b, c, d or e), hide the classic CO2 value and display the new score
`https://world.openfoodfacts.org/api/v0/product/3414280980209.json?fields=ecoscore_grade` (Here it shows null)
- [ ] Please use the Nutri-Score visuals already in the app as placeholders until we have the visuals (so no change is necessary for the moment). 

The same actions have to be done on the summary tab, and on top of the `Environment` tab (where we also display the score)

### Placeholders with the right size

https://static.openfoodfacts.org/images/icons/ecoscore-a.svg
https://static.openfoodfacts.org/images/icons/ecoscore-b.svg
https://static.openfoodfacts.org/images/icons/ecoscore-c.svg
https://static.openfoodfacts.org/images/icons/ecoscore-d.svg
https://static.openfoodfacts.org/images/icons/ecoscore-e.svg
https://static.openfoodfacts.org/images/icons/ecoscore-unknown.svg

https://static.openfoodfacts.org/images/icons/ecoscore-a.png
https://static.openfoodfacts.org/images/icons/ecoscore-b.png
https://static.openfoodfacts.org/images/icons/ecoscore-c.png
https://static.openfoodfacts.org/images/icons/ecoscore-d.png
https://static.openfoodfacts.org/images/icons/ecoscore-e.png
https://static.openfoodfacts.org/images/icons/ecoscore-unknown.png

**Comment by teolemon** [comment]
(For reference, but not needed: he server side issue is: https://github.com/openfoodfacts/openfoodfacts-server/issues/4262)

**Comment by aleene** [comment]
Is there a sample product that can be used to check the implementation?

**Comment by teolemon** [comment]
I think @stephanegigandet deployed something. At least it's merged in master

**Comment by aleene** [comment]
Is there an icon/image for `No Eco-Score available`? We could start adding that in #714

**Comment by teolemon** [comment]
@aleene Placeholders with the right size are now available

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/97958008-a6813c80-1dac-11eb-8bca-4d336c10e85e.png)
Here's what it would look like with a placeholder. We would loose the product image for better legibility. cc @stephanegigandet @openfoodfacts/openfoodfacts-ios 
https://static.openfoodfacts.dev/images/icons/ecoscore-a.svg
https://static.openfoodfacts.dev/images/icons/ecoscore-b.svg
https://static.openfoodfacts.dev/images/icons/ecoscore-c.svg
https://static.openfoodfacts.dev/images/icons/ecoscore-d.svg
https://static.openfoodfacts.dev/images/icons/ecoscore-e.svg

**Comment by teolemon** [comment]
@aleene the Logos are available in prod, including the "not available" one.

Also for the offline mode, we're going to modify the CSV to add a column for the eco-score, and we'll need to:
- modify the realm schema
- modify the layout
- invalidate all the records
- load the new records with the eco-score

**Comment by teolemon** [comment]
Fixed by @aleene
