### ISSUE TITLE
Environment tab work

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-ios#796]
All the work, which involves the environment tab is currently spread over multiple issues and maybe incomplete. This issue is an attempt to get an overview of the status of the work.

- [X] #790 always show the environment tab. This is required before most of the other work can start. pull-request #794.
- [x] decode the packaging url from the json. There was an issue here: the url was not (yet) present in the selectedImages json field;
- [x] show the packaging image
- [x] allow uploading of packaging image (#749)
- [x] #749 show packaging field
- [x] remove packaging field from summary tab
- [x] add ecoscore images to assets
- [x] decode ecoScore from json
- [x] show ecoscore image in environment tab
- [ ] show ecoscore explanation (html?)
- [x] #775 allow editing of labels, which required to get correct ecoscore calculations.
- [x] #765 dark mode support from the start
- [ ] #729 add all ecoscore supplychain issues in environment tab?
- [x] modify the realm schema
- [ ] modify the layout
- [ ] invalidate all the records
- [ ] load the new records with the eco-score
- [ ] add the required translations
- [x] link to ecoscore page

Related

- [x] #744 ecoScore on the scan screen

**Comment by aleene** [comment]
How
