### ISSUE TITLE
Automatic screenshot generation (tracker issue)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#913]
### What
- [ ] #914
- [ ]  Fix the "Scan screenshot" generation
  - [ ] Add a way to set the background of the barcode scanner with an arbitrary image, per country
- [ ] #915
- [ ] #916
- [ ]  Add `fastlane frameit` to the Fastlane file, so that we can get versions wrapped in physical devices
- [ ] #917
- [ ]  Ensure we can generate for 1 of (iPhone 11 Pro Max, iPhone 11, iPhone XS Max, iPhone XR), 1 of (iPhone 6s Plus, iPhone 7 Plus, iPhone 8 Plus), 1 of (3rd generation iPad Pro)
- [ ]  Extra: For debugging purposes, it would be great to have other screen resolutions (iPhone 11 Pro, iPhone X, iPhone XS) (iPhone 6, iPhone 6s, iPhone 7, iPhone 8) (iPhone SE) (iPhone 4s)
- [ ] #893

### Part of
- #912
