### ISSUE TITLE
Keep dependancies up to date (Tracker)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#925]
### What
- [ ] Alamofire: new version 5.4.3
- [ ] BulletinBoard: new version 5.0.0
- [ ] KeychainAccess: new version v4.2.2
- [ ] FloatingPanel: new version 2.4.0
- [ ] OHHTTPStubs: new version 9.1.0
- [ ] Kingfisher: new version 6.3.1
- [ ] NotificationBanner: new version 3.0.6
- [ ] Zip: new version 2.1.1
- [ ] sentry-cocoa: new version 7.2.9
- [ ] realm-cocoa: new version v10.14.0
- [ ] swifter: new version 1.5.0
- [ ] IQKeyboardManager: new version v6.5.6
- [ ] XCGLogger: new version 7.0.1
- [ ] Nimble: new version v9.2.1
- [ ] AlamofireImage: new version 4.2.0
- [ ] TOCropViewController: new version 2.6.0
- Ensure that we don't needlessly bump the iOS minimum version, excluding devices from the update

### Part of
- #912

**Comment by morganzellers** [comment]
I think I'm gonna take a look at this - could you add a hacktoberfest label? :D

**Comment by teolemon** [comment]
done @morganzellers 
Can you balance upgrades with device support ?

**Comment by morganzellers** [comment]
> done @morganzellers Can you balance upgrades with device support ?

Possibly - what are you needing done for support?
